/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExpectedSessionVersion = number;
export type OperationId = string;
export type RequestId = string;
export type CreatedAt = string;
export type Cursor = number;
export type EventId = string;
export type RouteDeckEventType =
  | "session_created"
  | "projection_changed"
  | "navigation_changed"
  | "operation_changed"
  | "private_form_changed"
  | "turn_started"
  | "turn_finalized"
  | "turn_interrupted";
export type Name = string;
export type Details = PublicValue[];
export type EntityKind = string;
export type Handle = string;
export type Values = PublicValue[];
export type EntityHandles = PublicEntityHandle[];
export type Code = string;
export type CorrelationId = string;
export type FailureKind =
  | "contract"
  | "state_conflict"
  | "context_provider"
  | "guard"
  | "review"
  | "transport"
  | "provider_protocol"
  | "business"
  | "persistence"
  | "external_outcome_unknown"
  | "internal";
export type OperationId1 = string | null;
export type Phase = string;
export type PublicMessage = string;
export type RecoveryDirective = string | null;
export type RequestId1 = string | null;
export type AffectedCapability = string | null;
export type DeliveryPhase = ("not_sent" | "possibly_sent" | "response_received") | null;
export type HttpStatus = number | null;
export type Provider = string | null;
export type ProviderCode = string | null;
export type NodeId = string | null;
export type OperationId2 = string | null;
export type RequestId2 = string | null;
export type StatusCode = string | null;
export type ProjectionVersion = number | null;
export type SessionVersion = number;
export type EntryNodeId = string;
export type Name1 = string;
export type DeepLinkPolicy = "shareable" | "session_bound";
export type Id = string;
export type OperationIds = string[];
export type RouteTemplate = string;
export type Active = string | null;
export type Detail = string[];
export type Diagnostic = string[];
export type Error = string[];
export type Form = string[];
export type Frame = string[];
export type Peer = string[];
export type Review = string[];
export type Status = string[];
export type Title = string;
export type Event = string;
export type Id1 = string;
export type Id2 = string;
export type Affordances = SurfaceAffordanceSpec[];
export type Component = string;
export type Id3 = string;
export type SurfaceLifecycle = "ephemeral" | "stable";
export type OperationId3 = string;
export type Outcome = string;
export type Source = string;
export type Target = string;
export type Transitions = FrontendTransitionContract[];
export type OperationDisposition =
  "completed" | "blocked" | "needs_input" | "requires_review" | "pending" | "failed" | "external_outcome_unknown";
export type AttemptId = string;
export type DeliveryPhase1 = "not_sent" | "possibly_sent" | "response_received";
export type OperationPhase =
  | "received"
  | "lease_acquired"
  | "validated"
  | "context_refreshed"
  | "guards_passed"
  | "review_staged"
  | "execution_claimed"
  | "tool_started"
  | "tool_succeeded"
  | "tool_failed"
  | "tool_outcome_unknown"
  | "execution_result_recorded"
  | "state_committed"
  | "completed";
export type Phases = OperationPhase[];
export type RequestFingerprint = string;
export type ResultFingerprint = string | null;
export type ResultId = string | null;
export type OperationSource = "surface" | "agent" | "system" | "route";
export type OperationId4 = string;
export type Outcome1 = string | null;
export type ProjectionVersion1 = number;
export type RequestId3 = string;
export type ExpiresAt = string;
export type Id4 = string;
export type SessionId = string;
export type SessionVersion1 = number;
export type Complete = boolean;
export type ExpectedSessionVersion1 = number;
export type RequestId4 = string;
export type NodeId1 = string;
export type RouteParams = PublicValue[];
export type CurrentNodeId = string;
export type DeclaredProviderIds = string[];
export type NavgraphVersion = string;
export type SchemaVersion = number;
export type Entities = PublicEntityHandle[];
export type EventCursor = number;
export type RouteDeckInteractionOwnerType = "chat" | "surface" | "review" | "system" | "navigation";
export type RouteDeckInteractionPhase = "idle" | "active";
export type OperationId5 = string;
export type ReviewRequired = boolean;
export type SafetyClass = string;
export type Title1 = string;
export type LegalOperations = ProjectedOperation[];
export type BackNodeId = string | null;
export type CanBack = boolean;
export type CanCancel = boolean;
export type CanForward = boolean;
export type CancelTargetNodeId = string | null;
export type CurrentEntryId = number;
export type ForwardNodeId = string | null;
export type ResumeHandle = string | null;
export type RouteTemplate1 = string;
export type ProjectionVersion2 = number;
export type SessionVersion2 = number;
export type Code1 = string;
export type Message = string | null;
export type ActionId = string;
export type Label = string;
export type OperationId6 = string;
export type SuggestedActions = ProjectedSuggestedAction[];
export type Component1 = string;
export type Props = PublicValue[];
export type SurfaceId = string;
export type Detail1 = ProjectedSurface[];
export type Diagnostic1 = ProjectedSurface[];
export type Error1 = ProjectedSurface[];
export type Form1 = ProjectedSurface[];
export type Frame1 = ProjectedSurface[];
export type Peer1 = ProjectedSurface[];
export type Review1 = ProjectedSurface[];
export type Status1 = ProjectedSurface[];
export type ExpectedSessionVersion2 = number;
export type RequestId5 = string;

/**
 * Schema catalog consumed by the headless TypeScript package.
 */
export interface RouteDeckTransportContracts {
  dispatch_request: DispatchRequest;
  event: PublicRouteDeckEvent;
  failure: RouteDeckFailure;
  frontend_contract: FrontendContract;
  operation_result: OperationResult;
  private_form_write_request: PrivateFormWriteRequest;
  public_projection: PublicProjection;
  review_request: ReviewRequest;
}
export interface DispatchRequest {
  arguments?: Arguments;
  expected_session_version: ExpectedSessionVersion;
  operation_id: OperationId;
  request_id: RequestId;
}
export interface Arguments {
  [k: string]: unknown;
}
/**
 * SSE-safe event contract with the private session identifier removed.
 */
export interface PublicRouteDeckEvent {
  created_at: CreatedAt;
  cursor: Cursor;
  event_id: EventId;
  event_type: RouteDeckEventType;
  payload: PublicEventPayload;
  projection_version?: ProjectionVersion;
  session_version: SessionVersion;
}
export interface PublicEventPayload {
  details?: Details;
  entity_handles?: EntityHandles;
  failure?: RouteDeckFailure | null;
  node_id?: NodeId;
  operation_id?: OperationId2;
  request_id?: RequestId2;
  status_code?: StatusCode;
}
export interface PublicValue {
  name: Name;
  value: Value;
}
export interface Value {
  [k: string]: unknown;
}
export interface PublicEntityHandle {
  entity_kind: EntityKind;
  handle: Handle;
  values?: Values;
}
export interface RouteDeckFailure {
  code: Code;
  correlation_id: CorrelationId;
  kind: FailureKind;
  operation_id?: OperationId1;
  phase: Phase;
  public_message: PublicMessage;
  recovery_directive?: RecoveryDirective;
  request_id?: RequestId1;
  safe_details?: FailureSafeDetails;
}
export interface FailureSafeDetails {
  affected_capability?: AffectedCapability;
  delivery_phase?: DeliveryPhase;
  http_status?: HttpStatus;
  provider?: Provider;
  provider_code?: ProviderCode;
}
export interface FrontendContract {
  entry_node_id: EntryNodeId;
  name: Name1;
  nodes: Nodes;
  surfaces: Surfaces;
  transitions: Transitions;
}
export interface Nodes {
  [k: string]: FrontendNodeContract;
}
export interface FrontendNodeContract {
  deep_link_policy: DeepLinkPolicy;
  id: Id;
  operation_ids: OperationIds;
  route_template: RouteTemplate;
  surfaces: FrontendSurfaceSlots;
  title: Title;
}
export interface FrontendSurfaceSlots {
  active: Active;
  detail?: Detail;
  diagnostic?: Diagnostic;
  error?: Error;
  form?: Form;
  frame?: Frame;
  peer?: Peer;
  review?: Review;
  status?: Status;
}
export interface Surfaces {
  [k: string]: FrontendSurfaceContract;
}
export interface FrontendSurfaceContract {
  affordances?: Affordances;
  component: Component;
  id: Id3;
  lifecycle: SurfaceLifecycle;
  public_props_schema: PublicPropsSchema;
}
export interface SurfaceAffordanceSpec {
  event: Event;
  id: Id1;
  operation?: OperationRef | null;
}
export interface OperationRef {
  id: Id2;
}
export interface PublicPropsSchema {
  [k: string]: unknown;
}
export interface FrontendTransitionContract {
  operation_id: OperationId3;
  outcome: Outcome;
  source: Source;
  target: Target;
}
export interface OperationResult {
  disposition: OperationDisposition;
  evidence: OperationEvidence;
  failure?: RouteDeckFailure | null;
  operation_id: OperationId4;
  outcome?: Outcome1;
  projection_version: ProjectionVersion1;
  request_id: RequestId3;
  review?: OperationReview | null;
  session_id: SessionId;
  session_version: SessionVersion1;
}
export interface OperationEvidence {
  attempt_id: AttemptId;
  delivery_phase?: DeliveryPhase1 | null;
  phases: Phases;
  request_fingerprint: RequestFingerprint;
  result_fingerprint?: ResultFingerprint;
  result_id?: ResultId;
  source: OperationSource;
}
export interface OperationReview {
  expires_at: ExpiresAt;
  id: Id4;
}
export interface PrivateFormWriteRequest {
  complete?: Complete;
  expected_session_version: ExpectedSessionVersion1;
  request_id: RequestId4;
  value: Value1;
}
export interface Value1 {
  [k: string]: unknown;
}
export interface PublicProjection {
  current: ProjectionLocation;
  diagnostics: ProjectionDiagnostics;
  entities: Entities;
  event_cursor: EventCursor;
  failure?: RouteDeckFailure | null;
  interaction: RouteDeckInteractionState;
  legal_operations: LegalOperations;
  navigation: ProjectedNavigation;
  projection_version: ProjectionVersion2;
  session_version: SessionVersion2;
  status: ProjectionStatus;
  suggested_actions: SuggestedActions;
  surfaces: ProjectedSurfaceSlots;
}
export interface ProjectionLocation {
  node_id: NodeId1;
  route_params?: RouteParams;
}
export interface ProjectionDiagnostics {
  current_node_id: CurrentNodeId;
  declared_provider_ids?: DeclaredProviderIds;
  navgraph_version: NavgraphVersion;
  schema_version: SchemaVersion;
}
export interface RouteDeckInteractionState {
  owner?: RouteDeckInteractionOwnerType | null;
  phase?: RouteDeckInteractionPhase;
}
export interface ProjectedOperation {
  operation_id: OperationId5;
  review_required?: ReviewRequired;
  safety_class: SafetyClass;
  title: Title1;
}
export interface ProjectedNavigation {
  back_node_id?: BackNodeId;
  can_back: CanBack;
  can_cancel: CanCancel;
  can_forward: CanForward;
  cancel_target_node_id?: CancelTargetNodeId;
  current: ProjectionLocation;
  current_entry_id: CurrentEntryId;
  forward_node_id?: ForwardNodeId;
  resume_handle: ResumeHandle;
  route_template: RouteTemplate1;
}
export interface ProjectionStatus {
  code?: Code1;
  message?: Message;
}
export interface ProjectedSuggestedAction {
  action_id: ActionId;
  arguments?: Arguments1;
  label: Label;
  operation_id: OperationId6;
}
export interface Arguments1 {
  [k: string]: unknown;
}
export interface ProjectedSurfaceSlots {
  active: ProjectedSurface | null;
  detail?: Detail1;
  diagnostic?: Diagnostic1;
  error?: Error1;
  form?: Form1;
  frame?: Frame1;
  peer?: Peer1;
  review?: Review1;
  status?: Status1;
}
export interface ProjectedSurface {
  component: Component1;
  props?: Props;
  surface_id: SurfaceId;
}
export interface ReviewRequest {
  expected_session_version: ExpectedSessionVersion2;
  request_id: RequestId5;
}
