services:
  routedeck-backend:
    build:
      context: ../..
      dockerfile: examples/minimal-fastapi-react/backend/Dockerfile
    ports:
      - "8096:8096"

  routedeck-frontend:
    build:
      context: ../..
      dockerfile: examples/minimal-fastapi-react/frontend/Dockerfile
    environment:
      ROUTEDECK_BACKEND_URL: http://routedeck-backend:8096
    depends_on:
      - routedeck-backend
    ports:
      - "5190:5190"
